services:
  php:
    container_name: projet-php
    # image: php:8.2-apache
    build:
      context: conf/php/
    restart: on-failure
    ports:
      - 50180:80
    volumes:
      - ./backend:/var/www/html
      # :rw,exec
    command: /bin/bash -c "chown -R :www-data /var/www/html/ && chmod -R g+w /var/www/html && apache2-foreground"
